using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SwordControl : MonoBehaviour
{
    //vnu
    public GameObject Sword;
    //rgg隔の最小
    public float minTime = 0.3f;
    //rgg隔の最大
    public float maxTime = 2.5f;
    //成成rgg隔
    private float interval;
    //U^rg
    private float time = 0f;

    public float RotateMin = 0f;
    public float RotateMax = 360f;
    private void Start()
    {
        interval = GetRandomTime();
    }

    // Update is called once per frame

    private void Update()
    {
        //rgy
        time += Time.deltaTime;
        float z = Random.Range(RotateMin, RotateMax);

        //U^rgが生成rgになったとき(生成rgより大きくなったとき)
        if (time > interval)
        {
            //インスタンス化する(生成する)
            GameObject NewSword = Instantiate(Sword);
            //生成した长巫摔Q定する
            NewSword.transform.position = new Vector3(0, 2, 5);
            NewSword.transform.Rotate(0, 0, z);
            time = -999999999999999999;
        }
    }

    //ランダムなrgを生成するv数
    private float GetRandomTime()
    {
        return Random.Range(minTime, maxTime);
    }
    
}
